export const startupDescription = {
    nossaRoca: "O Nossa Roça é um aplicativo mobile desenvolvido para auxiliar agricultores familiares na comercialização de suas colheitas excedentes de forma simples, direta e acessível. A plataforma permite que o agricultor cadastre os alimentos disponíveis e os ofereça para pequenos comércios locais, como mercadinhos, feiras e restaurantes da região. O próprio agricultor fica responsável pela entrega no local combinado. Além de facilitar a venda, o aplicativo contribui para reduzir o desperdício de alimentos e fortalecer a economia local, promovendo a geração de renda para as famílias agricultoras e o acesso a produtos frescos para os compradores. Futuramente, o Nossa Roça também poderá incluir funcionalidades de doação para pessoas físicas e instituições sem fins lucrativos.",

    aromasDoVale: "Espera-se expandir para a escala comercial, a extração, padronização e comercialização do produto: óleo essencial das cascas de laranja, por meio de métodos tradicionais, reconhecidos e de expertise das proponentes. A fim de converter um resíduo agroindustrial em um produto com demanda e de alto valor de mercado.",

    ArtEsfera: "A plataforma ArtEsfera irá contar com três pilares validados em entrevistas com o público-alvo: Assistente Virtual Inteligente (Daeva): No protótipo, usando o modelo GPT-4, a Daeva atenderá a três demandas centrais: orientação sobre procedimentos jurídicos (direitos autorais, contratos), auxílio na construção de precificação justa e elaboração de estratégias de marketing. Bilheteria Virtual: Permitirá que qualquer profissional crie seu evento e venda ingressos diretamente pela plataforma, com uma taxa de serviço variável e justa, incentivando o uso por artistas em todos os estágios de carreira. Dashboard de Cursos: Um espaço onde usuários poderão submeter e vender cursos voltados à profissionalização no setor cultural (mediante curadoria), além de cursos próprios financiados pela ArtEsfera sobre estratégias de crescimento e empreendedorismo para os assinantes. Desta forma, acreditamos que esses três pilares serão capazes de impactar a cena artística e cultural do Estado e do Brasil, diminuindo as desigualdades existentes do cenário, gerando trabalho e educação de qualidade para esses profissionais.",

    zilly: "Nosso produto é um sistema de monitoramento estrutural composto por sensores físicos instalados em pontos estratégicos de edificações, como pilares, vigas e lajes, bem como em infraestruturas essenciais, como pontes e viadutos. Esses sensores captam em tempo real dados sobre deformações, vibrações, deslocamentos e possíveis anomalias na estrutura. As informações são transmitidas para uma plataforma digital, onde são processadas e analisadas por algoritmos de inteligência artificial que realizam análise preditiva para antecipar falhas e padrões de risco. O sistema gera alertas automáticos quando há perigo, além de relatórios técnicos e gráficos que permitem acompanhamento remoto e contínuo da saúde estrutural, oferecendo uma solução eficiente para manutenção preditiva, redução de riscos e otimização de custos.",

    hibuddy: "O Edubuddy é um aplicativo educativo baseado em inteligência artificial que utiliza elementos de gamificação para ensinar conteúdos escolares a crianças do ensino infantil e fundamental I. Inspirado em jogos como o “Pou”, o app oferece uma experiência interativa onde a criança aprende brincando, com atividades adaptadas ao seu nível de conhecimento e estilo de aprendizagem. A IA funciona localmente no dispositivo, garantindo maior privacidade e acessibilidade. O objetivo é tornar o processo de aprendizagem mais divertido, inclusivo e eficiente — inclusive para crianças neurodivergentes.",

    desvenda: "Desvenda é um aplicativo mobile que atua como um guia inteligente de experiências locais, conectando usuários a eventos, gastronomia, cultura e lazer com base em geolocalização e preferências pessoais. Por meio de uma interface moderna e inspirada em redes sociais, o app permite buscar, filtrar e interagir com rolês próximos, promovendo descobertas personalizadas, planejamento de agenda e integração com rotas de transporte. Além de atender o público em busca de novas vivências, o Desvenda oferece espaço para estabelecimentos e produtores locais divulgarem seus serviços de forma segmentada e eficiente, fortalecendo a economia criativa e o turismo regional.",

    sera462: "O SERA462 é uma plataforma gamificada de educação que integra o conteúdo escolar a uma experiência imersiva em formato de jogo, onde os alunos desvendam os mistérios do planeta SERA462 ao responderem atividades propostas pelos professores. Com o apoio de uma inteligência artificial, os professores criam e personalizam questões que são inseridas automaticamente no game. Além disso, a plataforma permite que professores e gestores acompanhem o desempenho dos alunos em tempo real, promovendo maior engajamento, eficiência e personalização no processo de ensino-aprendizagem.",

    roleApp: "Rolê App é uma plataforma digital de curadoria colaborativa que conecta usuários a experiências autênticas de lazer (bares, eventos culturais, passeios) em tempo real. Como funciona: Para usuários: Busca personalizada por localização, tipo de experiência e orçamento. Recomendações baseadas em machine learning e avaliações da comunidade. Atualizações dinâmicas de eventos e promoções. Para estabelecimentos: Perfil digital com gestão de eventos, promoções e analytics de público. Planos de assinatura para maior visibilidade (ex.: destaque no app).",

    serFit: "Soluciona o problema descrito por vários pacientes na hora da correria do dia a dia ter que escolher o alimento por aplicativo e não ter uma variedade de fast food fit e comidas saudáveis, principalmente para quem quer aderir a nova onda do momento que é ser Fit, ou está no processo de reeducação alimentar e entra nos aplicativos tradicionais e são tentados a escolher o que já de costume escolherem ou seja o não saudável.",

    lamparinaSocial: "O serviço envolve a formação continuada de professores durante a implementação de um programa de educação midiática que envolve o uso de softwares livres para a criação de uma rede social escolar, cujo objetivo é promover a colaboração, a aprendizagem significativa, o letramento digital e o fortalecimento dos vínculos entre a comunidade escolar através de práticas de autogestão desta rede.",

    mype: "O produto é uma plataforma de performance e treino inteligente, entregue via um software em aplicativo mobile. O serviço utiliza visão computacional avançada para transformar a câmera do smartphone em um laboratório de biomecânica pessoal. O processo começa com um mapeamento da estrutura corporal e fisiologia do usuário. Durante o treino, nosso algoritmo analisa cada repetição em tempo real, focando em métricas cruciais de performance como execução, cadência, amplitude e controle do movimento. Além de orientações instantâneas por áudio e alertas visuais para correção imediata, o usuário recebe relatórios detalhados e replays em vídeo de suas séries. Esses vídeos destacam os pontos de falha e acerto, permitindo uma análise precisa para otimizar a técnica. Essencialmente, resolvemos a falta de orientação de elite, maximizando a performance e a segurança do treino de forma totalmente personalizada, mediante as particularidades fisicas e objetivos do usuário.",
        

}